name: CI (PR created/changed)

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      key:
        description: "AWS Access Key Id."
        required: true
        default: ""
      secret:
        description: "AWS Access Key Secret."
        required: true
        default: ""
      token:
        description: "AWS Session Token."
        required: true
        default: ""
      # region:
      #   description: "AWS Region."
      #   required: true
      #   default: "eu-north-1"
      environment:
        description: "AWS environment"
        required: true
        default: "dev"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          pulumi_access_token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          aws_access_key_id: ${{ github.event.inputs.key }}
          aws_secret_access_key: ${{ github.event.inputs.secret }}
          aws_session_token: ${{ github.event.inputs.token }}
          # aws_region: ${{ github.event.inputs.region }}
          stack: ${{ github.event.inputs.environment }}


      - name: Install deps
        run: pip install --upgrade pip && pip install dagger-io
      - name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
      - name: Run Dagger pipeline
        run: dagger run python ci/main.py --pulumi_token $pulumi_access_token --aws_id $aws_access_key_id --aws_secret $aws_secret_access_key --aws_token $aws_session_token --stack $stack
